### ISSUE TITLE
Role-Based Interaction

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#102]
Für das geführte Einhalten des Workflows, soll anhand der Rolle bestimmte Aktionen möglich und nicht möglich sein.

**In PB**
- [x] PO darf Cards löschen, bearbeiten und erstellen

- [x]  Alle anderen dürfen Card (Details einsehbar) lesen

- [x] Fehlermeldung anziegen, das keine berechtigung als nicht PO

**Archiv Board**

- [x] All können nur lesend zugreifen

- [x] System hat Zugriff für Automatik funktionen

**Comment by husKyRe** [comment]
@Hermann Hier könnte es auch sinnvoll sein, dass die Lanes typen bekommen.

**Comment by TheDream3r** [comment]
@husKyRe: Darf ein User andere User der Task zuweisen, oder darf das nur der PO?

**Comment by husKyRe** [comment]
@TheDream3r im ProductBacklog darf nur der PO die Änderungen vornehmen. Im SprintBacklog dürfen die User auch den Task anderen Usern zuweisen und ergänzungen vornehmen am Task, wie z.b. Steps hinzufügen oder abhaken
