### ISSUE TITLE
Detailansicht Sprint

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#103]
Die Detailansicht soll einerseits für das erstellen von den Sprintdaten unterstützen, andererseits die Sprint daten entsprechend anzeigen. Damit alle Projektbeteiligen über den Rahmen des Sprints bescheid wissen.

Außerdem kann hier ein sprint freigegeben werden für den forlauf des Prozesses

**Sprintdaten**
- Sprintnummer (fortlaufend von System vergeben)
- Startdatum (berechnet)
- enddatum (berechnet)
- Dauer in Tage (vorbelegt, mit standard wert aus projekt)
- Sprint Story (mehrzeiliges Textfeld)
- Status
- vorgesehene Produkt version
- verbleibende Dauer, wenn Status des Sprints größer planned ist

**Comment by FunkyVonTunky** [comment]
![Info-und-Statistik](https://user-images.githubusercontent.com/61056122/98572216-aa81f280-22b5-11eb-9543-cb639478dd23.png)

**Comment by FunkyVonTunky** [comment]
![Info-und-Statistik_2](https://user-images.githubusercontent.com/61056122/98572654-2714d100-22b6-11eb-8fbe-a52d225dcaec.png)

**Comment by FunkyVonTunky** [comment]
![Planning_V2_Sprint-Details](https://user-images.githubusercontent.com/61056122/98574317-11081000-22b8-11eb-9ac4-a64117bd6830.png)
