### ISSUE TITLE
Projekt Erstellen erweitern

### ISSUE THREAD

**Issue by HD-plus** [scrmtl/server#104]
- [x] Es muss eine Auswahl einer Vorlage geben
   - [x] Backend muss eine Deep-Copy eine Projektes durchführen, bis zu Lanes-Ebene
   - [x] Es muss ein Query Parameter geben, über den die ID des Projektes, welches als Template dienen soll übergeben wird: ?template=id 
   - [x] Im Projekt erstellen Katalog wird ein Dropdown-Feld angezeigt, welches alle Template-Projekte anzeigt.
- [x] Ein Projekt muss als Vorlage kennzeichenbar sein
   - [x] In den Projekt Einstellungen kann ein Haken gesetzt werden, um ein Projekt als Template freizugeben
   - [x] Das Datenmodell muss um diesen Boolschen Wert ergänzt werden.
   - [x] Der Boolsche Parameter muss über die API freigegeben werden

- [x] Beim Anlagen eines Projektes muss der Anlegegende alle Rechte haben, also PO im Projekt sein
   - [x] Nach dem anlegen eines Projektes erzeugt das Backend automatisch über die ID des angemeldeten Benutzers den PO

**Comment by husKyRe** [comment]
customUrlFn in project bitte kommentare anpassen
