### ISSUE TITLE
Löschen von Projekten nicht möglich

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#120]
Das Backend verweigert mir die Aktion
Siehe Fehlermeldung

![grafik](https://user-images.githubusercontent.com/60154287/99948409-b8397c80-2d79-11eb-9ede-07d0c4e67867.png)

**Comment by HD-plus** [comment]
@husKyRe Das ist ein Feature. Weil das Projekt Archiviert ist, kann es nicht mehr geändert werden. Auch nicht gelöscht.
Wenn das anderes sein soll, würde ich das als Feature anstatt als Bug aufnehmen. Dann müsste auch nochmal das genau verhalten geklärt werden.

**Comment by husKyRe** [comment]
Übernahme der Anforderungen in ein neuen Issue #123 

Wurde als Bug abgelehnt.
