### ISSUE TITLE
Einfache Benutzerverwaltung für ein Projekt

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#14]
Als PO oder SM möchte ich gerne Personen zu einem Projekt hinzufügen. Die Personen werden in einem Projektteam oder Projektgruppe gesammelt. Einer Person innerhalb eines Projektes können Rollen zugeteilt werden.

Alle registrieren Personen sollen einem oder mehreren Projekte zuordbar sein.
Personen sollen anhand vom Vorname und/oder Nachname beim Hinzufügen zu einem Projekt gesucht werden können. Bei hinzufügen einer Person in ein Projekt soll Ihm gleich eine Rolle zugewiesen werden. Mehrfach Zuordnung von Rollen ist möglich

- [x] Rechteänderungen in Eigenschaften in Projektverwaltung

- [x] Anzeige bestehender Projekt users

- [x] Neue plattform user zu projet zuordnen

- [x] Rolle einstellbar

- [x] Project User löschen

- [x] Bug: Bei Fehler Ausgabe über Snackbar Dialog schließt sich ungewohlt (Mutation Error)

**Comment by husKyRe** [comment]
nur ein einfaches Team, dass aus Benutzern besteht

**Comment by husKyRe** [comment]
![grafik](https://user-images.githubusercontent.com/60154287/87256265-4f6bfa80-c491-11ea-9a1f-2505efbc0a3b.png)

**Comment by husKyRe** [comment]
V0.7 Nicht geschafft.
= Übernahme in nächsten Sprint

**Comment by FunkyVonTunky** [comment]
![Members](https://user-images.githubusercontent.com/61056122/97899605-ce838800-1d39-11eb-8244-ddaa769b11ef.png)
