### ISSUE TITLE
Authenifizierung von Benutzer

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#15]
Als User möchte ich mich anmelden können um das affengeile Angebot nutzen zu können. Um mich später möglichst einfach einloggen zu können wird der nickname als anmeldename verwendet, damit man auf alle Inhalte zugreifen kann. 

**Durch UI:**
- [x] Login Page mit Login 

- [x] Logout Funktion

- [x] Registrier - Funktion

**Durch Django Admin Page:**
- [x] Konto mit E-Mail, Vorname, Nachname,  anlegen/löschen/ändern
- [x] nickname setzen bei konto erstellung

**Comment by husKyRe** [comment]
**V0.7** Fehlt:
- Passwort ändern
- View zum ändern des Passwortes (Kombination mit User Information bei klick auf User Icon)
- Registrier - Funktion
=Übernahme in nächsten Sprint

**Comment by TheDream3r** [comment]
Das soll als eigener Task ausgelagert werden: 

- Passwort ändern
- View zum ändern des Passwortes (Kombination mit User Information bei klick auf User Icon)
