### ISSUE TITLE
Löschen von Task nicht möglich

### ISSUE THREAD

**Issue by TheDream3r** [scrmtl/server#151]
Beim Löschen eines Tasks im Product Backlog kommt die Meldung "Page not found" und der Task wird nicht gelöscht.

**Comment by zed92** [comment]
habe dies mit dem https://scrmtl.ddns.net/app#/project/1/ProductBacklog getestet
karten werden zwar gelöscht aber verschwinden erst beim Neuladen der Seite

**Comment by zed92** [comment]
Gleiches Problem tritt auch im Sprint Backlog auch. 
https://scrmtl.ddns.net/app#/project/1/SprintBacklog

Karten verschwinden erst wenn die Seite neu geladen wird oder zwischen den Ansichten hin und her geschalten wird

**Comment by zed92** [comment]
Task wird nun beim Löschen auch sofort aus den Lanes gelöscht
