### ISSUE TITLE
Companion-Smartphone App

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#30]
Die App soll ein guter Begleiter für die Mitglieder eines Scrum Teams sein, der alle im Laufenden hält und gewisse Funktionen für bestimmte Meetings bereit hält.

Alle Teammitglieder ein oder mehreren Projekten zugehörig sollen über eine Smartphone App Metadaten über Ihre Projekte (Mitglied in ein oder mehreren Projekte) Metadaten einsehen können. Diese Daten werden für das Smartphone optimiert dargestellt.

Ein weitere wichtige Funktion ist die Beteilung bei der Vergabe der Story Points im Abstimmmodus. Alle Teilnahmeberechtigten an der Abstimmung (wird von PO über die Plattform bestimmt) dürfen über web oder Smartphone an der Abstimmtung teilnehmen.
Die Anwender über die Smartphone App bekommen die Frage dargestellt und können dann die Antworten einsehen.
Haben Sie Ihre Antwort abgegeben, wird Ihnen das Ergebnis am Smartphone dargestellt.

**Metadaten:**
- Anzeigen aller Projekte in denen man Mitglied ist.
- Pro Projekt folgende Informationen visualiseren
  - Projektname
  - Projektstatus
  - Rolle in dem Projekt
  - akt. Sprint
  - geplante Sprintende-Datum des laufenden Sprints
  - geplante Sprintanfangs-Datum des nächsten Sprint
  - max. Sprint für dieses Projekt vorgesehen

**Planning Poker**
- Anzeige der Frage/Card
- Antwortmöglichkeiten
- Ergebnis Anzeige der Poker Runde
- Übersicht über alle anstehenden Abstimmungen

- [x] Planning Poker View mit Responesive Fähigkeit

- [x] Darstellung der gerade zu bewerten Card

- [x] SP als Antwortmöglichkeiten

- [x] Ergebnis/Status anzeigen

**Comment by TheDream3r** [comment]
<img width="316" alt="grafik" src="https://user-images.githubusercontent.com/33479148/104635710-95a15100-56a2-11eb-8dba-0498a3f27c98.png">

**Comment by TheDream3r** [comment]
@husKyRe : Hey Responsive Meister! Kann man Die beiden Blöcke einfach untereinander machen? Dann wäre doch der ganze Task gegessen!

**Comment by husKyRe** [comment]
@TheDream3r  erledigt
