### ISSUE TITLE
Grundlegende Detailansicht für Task

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#42]
Ich möchte als User, die Details von meinen Karten bearbeiten. Je nach Board (SB oder PB) verschiedenen Content angeben. Ein Task besitzt eine oder mehrere Steplists, diese sind eine einfache ToDo Liste, die mit s.g. Steps befüllt werden kann. 
Zusätzlich soll die Task Card mit einem Status gekennzeichnet werden, ob diese vollständig abgeschlossen ist und abgenommen wurde.

Beim Anlegen eines Task muss ich min. einen Titel vergeben

Folgende Eigenschaften hat ein Task und kann vergeben werden
- [x] Label zuordnen
- [x] Beschreibungsfeld bearbeiten
- [x] Titel bearbeiten
- [x] Story Points setzen via Drop Down und es sind nur folgende Werte erlaubt: 0, 1, 2, 3, 5, 8, 13, 21, 34, 55 -> 0 ist Default beim Anlegen eines Tasks @HD-plus 
- [x] Anlegen/Verschieben/löschen von Steps @HD-plus 
- [x] Setzen des Stutus der Task Card an sich

**Detailanischt Task**

- Titel
- Beschreibung
- Label
- Ablage
- ID (nur lesend)
- SP (Vergeben)
- n Steplisten innerhalb eines Tasks möglich
- Anlegen/Verschieben/löschen von Steplisten
- Anlegen/Verschieben/löschen von Steps
- Status setzen von den Steps (abgeschlossen, in arbeit, offen)

**Comment by husKyRe** [comment]
Detail Ansicht der Tasks
![grafik](https://user-images.githubusercontent.com/60154287/77348979-9f844d00-6d3a-11ea-8c05-50a9aacdca73.png)

**Comment by husKyRe** [comment]
Detailansicht der Features
![grafik](https://user-images.githubusercontent.com/60154287/77349030-b0cd5980-6d3a-11ea-92bb-089273122e89.png)

**Comment by husKyRe** [comment]
Detailansicht der Epics
![grafik](https://user-images.githubusercontent.com/60154287/77349087-c5a9ed00-6d3a-11ea-8eeb-ff1e300aaa4a.png)

**Comment by husKyRe** [comment]
Folgende SP sind zulässig 1 2 3 5 8 13 21 34 55

**Comment by husKyRe** [comment]
Statis definieren bzw. mit Hermann klären

**Comment by FunkyVonTunky** [comment]
![Uploading Bildschirmfoto 2020-05-24 um 19.35.30.png…]()

**Comment by FunkyVonTunky** [comment]
Epic-Details:
![Bildschirmfoto 2020-05-24 um 19 35 30](https://user-images.githubusercontent.com/61056122/82761247-9f1b3780-9df9-11ea-91da-150534d963e0.png)

Feature-Details:
![Bildschirmfoto 2020-05-24 um 19 35 40](https://user-images.githubusercontent.com/61056122/82761260-b2c69e00-9df9-11ea-8761-17d8aa042385.png)

Task-Details
![Bildschirmfoto 2020-05-24 um 19 37 52](https://user-images.githubusercontent.com/61056122/82761265-ba864280-9df9-11ea-839e-0a8d8d2abd72.png)

**Comment by husKyRe** [comment]
Farbe des Labels werden Random auom. erzeugt. (Farben der UI sind ausgeschlossen)

**Comment by husKyRe** [comment]
Steplisten werden rausgenommen im Front end. Nur eine Stepliste ist Defaultmäßig angelegt.
