### ISSUE TITLE
Sprint Planning View

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#6]
Verknüfung von Elementen zwischen PB und SB.

Für die bessere Übernahme von Cards aus PB in SB. Soll es eine eigne Ansicht geben für PO und Dev Team für die bessere Plannung der Sprint bzw. Produkt-Versionen.

Aus dem **PB** wird die Growning  Lane angezeigt und die Ready (for Sprint) Lane:
- Die Growning  Lane wird für das Zurücklegen von Cards angeboten, wenn Details fehlen, Unterteilung zu grob oder vom Team abgelehnt
- Die Ready (for Sprint) Lane werden, die aus dem Refinement fertig formulierten Epic, Features und Tasks angezeigt. Aus der Ready (for Sprint) Lane können Elemente für die Sprint Plannung verwendet werden.

Es wird dann eine virtuelle Next Lane aus dem SB für die nächsten Sprints inkl. Sprintnummer (und Anfangsdatum) angezeigt und dadurch geplant. Es werden dadruch die nächsten Next Lanes des SBs erstellt. Es entstehen sozusagen virtuelle Next Lane der nächsten Sprints für das SB

Nun kann das Team das Sprint Planning für den nächsten Sprint machen und Themen die Sie auf den übernächsten legen wollen.

Damit man die Sprints gut planen kann, kann der PO ein neuen Sprint anlegen, mit Startdatum, Dauer (Vorbelegung durch Projekteinstellungen) und Enddatum. Zusätzlich kann die Versionsnummer vergeben werden. E
- [x] In der Sprint planning View sollen nur der akt. laufender Sprint und die zukünftigen Sprints und die vergangenen Sprints in absteigender Reihenfolge angezeigt werden.

- [x] Nur bewertete Cards (SP) können in einen Sprint gezogen werden.

  - [x] Cards, die in einen Sprint verplannt sind, ändern Ihren Status entsprechend nach Status Modell automatisch

- [x] Responsive Unterstützung für Planning View

- [x] Per Drag & Drop können die Cards den Sprints zuordenen.

- [x] Ist man mit dem Planning fertig muss der Sprint als freigegeben markiert werden. Damit später die Cards autom. verschoben werden.

- [x]  Ein Sprint kann solange bearbeitet werden bis dieser gestartet ist. Bei Änderungen muss erneut der Sprint freigegeben werden. Bei Status Done kann keine Ändeurng mehr vorgenommen werden

- [x] Filter schaffen für Cards nach den Kriterien (Board, Laneaufenthaltsort und Status) -> Für UI (Sprint Planning View) 

**Bedingungen**

-	Sprint im Status „_In Planning_“ können Task-Card hinzugefügt werden
-	Sprint im Status „_Planned_“ kann die Sprint Planning Automatik (Flow)
-	Solang Sprint nicht begonnen „_In Progress_“ (oder Folgezustande aus Sequenzdiagramm), kann zwischen den Status „In Planning“ und „Planned“ gewechselt werden
-	Sprint im Status „_Done_“ kann nur noch eine Task Card auf „_Accepted_“, „_Declined_“ oder „_Done_“ gesetzt werden.
-	Sprint im Status „_Accepted_“ kann keine Änderung mehr am Sprint und der Zuordnung der Task-Cards verändert werden

**Vorschlag 1**
![Planning_V2](https://user-images.githubusercontent.com/60154287/95125315-0e644900-0755-11eb-9b1e-0112d5c522f8.png)
**Vorschlag 2**
![Planning](https://user-images.githubusercontent.com/60154287/95125355-250aa000-0755-11eb-8eb3-ab127effc611.png)

**Comment by husKyRe** [comment]
- [ ] Geplannte Next Lanes der zukünftigen Sprints ausgegraut im SB anzeigen?
- [ ] Wann sollen die geplannte Next Lanes aktiv werden?

- [ ] Links von der akt. Next Lane in SB

**Comment by husKyRe** [comment]
Für weitere Interaktion fehlt Detailview von Sprint

**Comment by husKyRe** [comment]
Filterfunktion von Tasks in Lane fehlt, wenn Lane im linked Modus

Hier muss die Lanne alle Tasks Ausblenden die ver plant sind in einem Sprint

**Comment by husKyRe** [comment]
@HD-plus verschieben von Tasks wenn ein sprint auf Status _planned_ steht und das Start Datum des sprint erreicht ist, wäre eine gute aufgabe für das Backend

**Comment by HD-plus** [comment]
> @HD-plus verschieben von Tasks wenn ein sprint auf Status _planned_ steht und das Start Datum des sprint erreicht ist, wäre eine gute aufgabe für das Backend

Ja habe automatische Aufgaben schon aufgenommen 😁. Schaue mir das am Wochenende an.

**Comment by husKyRe** [comment]
@HD-plus Ist der Sprint schreibgeschützt, wenn dieser auf planned gesetzt ist?

**Comment by HD-plus** [comment]
> @HD-plus Ist der Sprint schreibgeschützt, wenn dieser auf planned gesetzt ist?

Nein ist er nicht Schreibschutz gibt es bis jetzt nur für Archivierte Projekte

**Comment by TheDream3r** [comment]
@husKyRe : Beim Review ist mir aufgefallen, dass es ja keine Filter gibt, oder ich die nicht finde. Aber brauchen wir überhaupt Filter? (Ich habe mal den einen Hacken entfernt) 

Wenn die Filter wegfallen können, dann kann der Task auf Done ;)

**Comment by husKyRe** [comment]
@TheDream3r Die Filter sind nicht direkt ersichtlich aber die Lanes _Growing_ und _Ready for Sprint_ werden entsprechend nach den Angaben gefiltert. Der Filter ist in der UI implementiert, wenn man die Lane Komponente im PlanningMode aufruft.
