### ISSUE TITLE
Globale Benutzerverwaltung

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#64]
Als Admin möchte ich gerne Personen auf der Plattform Scrum Tool registrieren. Hierfür benötige ich eine E-Mail Adresse, Vor- und Nachnamen.
Der Admin kann auch weitere Personen zum Admin ernennen und Personen von der Plattform löschen.

Der neue Benutzer kann dann auf einer Registerseite sein Passwort und nickname vergeben.
Der nickname muss system eineindeutig sein.
Der Benutzer kann selbstständig sein Passwort zurücksetzen, wenn er es vergessen hat.

In den Card werden die Initalien aus Vor- und Nachname gebildet und angezeigt, sodass einem Task ein oder mehrere Personen zugeordnet werden kann.

Der Admin kann einsehen, welcher Benutzer in welchen Projekt hinterlegt ist. Ein Benutzer kann mehreren Projekten in unterschiedlichen Rollen zugeordnet sein.

Django Admin Page:
- Benutzer anlegen/löschen (kann Admin)

Front End:
- Passwort ändern
- Anmeldefunktion
- Personen einem Projekt oder mehreren Projekt zuordnen (kann Admin oder PO, SM)
- Rollen vergeben (kann Admin oder PO, SM)
- Personen einer TaskCard hinzufügen/löschen (können alle)

Backend:

1. Im Model die Benutzterrollen hinterlegen:

Folgende Rollen gibt es in einem Projekt:
- [x] PO
- [x] SM
- [x] DEV

Folgende Rollen auf Plattform:
- [x] Admin
- [x] Standard

Ein Projekt hat einen Projektbenutzer:
- [x] dieser hat PK zu Plattformbenutzer
- [x] dieser hat eine Rolle

- [x] Alle Objekte müssen einfachen Zugriff auf Projektbenutzer erlauben
- [x] Regeln anlegen, dass nur Projektmitglieder auf Projekt zugreifen dürfen

2. Funktionalität fürs Frontend anbieten:

- [x] Passwort ändern
- [x] Anmeldefunktion
- [x] Personen einem Projekt oder mehreren Projekt zuordnen (kann Admin oder PO, SM)
- [x] Rollen vergeben (kann Admin oder PO, SM)
- [x] Personen einer TaskCard hinzufügen/löschen (können alle)

**Comment by husKyRe** [comment]
Hoover über das Benutzer Icon mit weiteren Details zur Person eigener Issue

**Comment by FunkyVonTunky** [comment]
<img width="247" alt="Bildschirmfoto 2020-05-26 um 17 42 47" src="https://user-images.githubusercontent.com/61056122/82921160-5b9b0780-9f78-11ea-8f73-999fe0a431f1.png">

<img width="926" alt="Bildschirmfoto 2020-05-26 um 17 43 40" src="https://user-images.githubusercontent.com/61056122/82921289-81c0a780-9f78-11ea-8141-8c330f78858a.png">

<img width="937" alt="Bildschirmfoto 2020-05-26 um 17 44 02" src="https://user-images.githubusercontent.com/61056122/82921303-85ecc500-9f78-11ea-8948-602313f48195.png">

**Comment by FunkyVonTunky** [comment]
Btw: Adobe hat beim Xperience Designer (also mein Designprogramm) die Export-Funktionen in der kostenlosen Version kastriert... ich kann nur noch die ersten zwei Screens (LoginI) exportieren... insofern können wir das leider nicht mehr auslesen von den Daten her.... Ich schau mal ob es da Alternativen gibt. 
Daher gibts die Designs aktuell erstmal nur als Screenshot

**Comment by husKyRe** [comment]
@HD-plus Bei Abfrage von list users bekommt man zwar name und email, aber nicht die id, um bei read users eine id anzugeben zu können

**Comment by husKyRe** [comment]
@HD-plus warum sind die Benutzer in der api in der Mehrzahl und alles andere in der einzahl Board, steplist usw.

**Comment by HD-plus** [comment]
> @HD-plus Bei Abfrage von list users bekommt man zwar name und email, aber nicht die id, um bei read users eine id anzugeben zu können

Das schaue ich mir mal genauer an

**Comment by HD-plus** [comment]
![image](https://user-images.githubusercontent.com/60195758/87250720-2cc4ec00-c467-11ea-8e4f-998f6a48e03f.png)
Es können nun Benutzerrechte auch Instanz-bezogen vergeben werden.
Somit ist die Grundlage für Benutzerverwaltung gelegt.

**Comment by husKyRe** [comment]
![grafik](https://user-images.githubusercontent.com/60154287/87256244-2e0b0e80-c491-11ea-881d-a7d6cfa8bbcd.png)

**Comment by husKyRe** [comment]
Bearbeiten von Users als neuen Issue anlegen @husKyRe
