### ISSUE TITLE
Darstellung von Projektverwaltung

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#69]
**Anlegen**
Ich möchte als Admin an einer zentralen Stelle (Projektverwaltung) ein neues Projekt im System anlegen können. Beim Anlegen eines Projekt soll Informationen zu Projektanfang, Projektende, Beschreibung, Kontierungsnummer, DoR, DoD, Sprintlänge und Sprintanzahl hinterlegt werden. 
**Abschließen/Archivieren**
Wenn ein Projekt vom PO oder Admin als abgeschlossen deklariert wird, wird das Projekt als archiviert entsprechend enstprechend gekennzeichnet und als Schreibgeschützt dargestellt.
Dies kann der PO oder Admin in der zentralen Projektverwaltung erledigen

Folgende Eigenschaften werden einem Projekt hinzugefügt und sind notwendig beim Anlegen:
-

- [x]  Projektanfangsdatum (Pflichtfeld, Datum)
- [x] - Projektenddatum (Pflichtfeld, Datum)
- [x] - Beschreibung (optional, String, mehrzeilig)
- [x] - DoR (optional, String, mehrzeilig)
- [x] - DoD (optional, String, mehrzeilig)
- [x] - Sprintlänge (Angabe in Wochentagen (Mo-So)) (Pflichtfeld, Int)
- [x] - Sprintanzahl (Berechnet, Int)

Für die Eingabe der Eigenschaften beim Anlegen wird die #70 Ansicht (seitlicher Eigenschaftsdialog) verwendet nur dass auf die Pflichteingaben geprüft wird.

Für die nachträgeliche Änderung der Eigenschaften sollte auch wieder die #70 (seitlicher Eigenschaftsdialog)  Ansicht genutzt werden.

Admin:
- [x] Eine gemeinsame Liste für alle Projekte (aktive und archivierten Projekte).
- [x] Die Sortierung der Projektliste ist erste die aktiven Projekte und dann die archivierten Projekten absteigend kommen.
- [x] Funktion zur Neuerstellung eines Projekte (Nutzt die seitliche Darstellung der Eigenschaften)
- [x] Anzeige von Projekt-Eigenschaften inkl. Status

Standard:
- [x] Zentrale View für Projektverwaltung
- [x] Liste aller meiner Projekte (in denen man Mitglied ist für Standard USer) (Gleiche Sortierung wie bei Admin) 

- [x] Für Liste muss assigend User für die Projekte abgefragt werden können @HD-plus 

- [x] Anzeige von Projekt-Eigenschaften inkl. Status

Abhängigkeit: #11 #70

**Comment by husKyRe** [comment]
![grafik](https://user-images.githubusercontent.com/60154287/86622571-62c62400-bfc0-11ea-8ca9-c3c19dc1ae54.png)

**Comment by husKyRe** [comment]
![grafik](https://user-images.githubusercontent.com/60154287/86622615-783b4e00-bfc0-11ea-9fc5-8569522eba3e.png)

**Comment by husKyRe** [comment]
Erste Idee
![grafik](https://user-images.githubusercontent.com/60154287/87256221-fb611600-c490-11ea-9deb-fc763d9c678c.png)

**Comment by husKyRe** [comment]
Für den Standard User
![grafik](https://user-images.githubusercontent.com/60154287/87344334-8522e900-c54e-11ea-9727-39a9eb7910ef.png)

**Comment by husKyRe** [comment]
V0.7 Fehlt:
- Die Sortierung der Projektliste ist erste die aktiven Projekte und dann die archivierten Projekten absteigend kommen.
- Liste aller meiner Projekte (in denen man Mitglied ist für Standard User) (Gleiche Sortierung wie bei Admin)
- Sprintlänge (Angabe in Wochentagen (Mo-So)) (Pflichtfeld, Int)
- Sprintanzahl (Berechnet, Int)
= Übernahme in nächsten Sprint

**Comment by husKyRe** [comment]
Offene Punkte:

Liste aller meiner Projekte (in denen man Mitglied ist für Standard USer) (Gleiche Sortierung wie bei Admin)
Für Liste muss assigend User für die Projekte abgefragt werden können @HD-plus

-> Übernahme in V0.9

**Comment by FunkyVonTunky** [comment]
![Projektverwaltung](https://user-images.githubusercontent.com/61056122/97899279-603ec580-1d39-11eb-81f2-1e06d406f529.png)
