### ISSUE TITLE
Ablage von Sprintdaten

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#71]
Ich möchte als PO ein oder mehrere Sprints in einem Projekt definieren können. Bei der Definition eines Sprints werden die Projekteigenschaften zu Start, ende, sprintlänge usw. herangezogen.

Beim Anlegen eines Sprintes definiere ich die Versionsnummer und die Story des Sprintes wird als Text hinterlegt.

Ich kann innerhalb der Sprintplannung die einzelnen Cards aus dem PB aus der Ready Lane heranziehen für die Plannung.

Wird das Startdatum eines Sprint ereicht und ist als freigegeben deklariert, werden die definierten Cards ins SB übertragen und dadurch aus dem PB entnommen. Sprint wird mit Status Run gekennzeichnet. Solange der geplante Sprint nicht begonnen oder nicht freigegeben ist (Status InPlanning oder Released ), verbleiben die Cards im PB in der Ready Lane und die Cards werden mit einem Status "Planned" versehen.

- [x] Cards bekommen neue Statis für Sprint Planning und Interaktion 
- [x] Objektmodell erweitern um ein Sprintobjekt
- [x] Projekt bekommt eine weitere Liste von Sprintobjekten
- [x] Sprintstart und ende wird durch die Sprintdauer und den Projektstart berechnet

Eigenschaften von Sprintobjekt:
- Start (lesend, berechnet)
- Ende (lesend, berechnet)
- Gesamtdauer (lesend, berechnet)
- Restdauer (lesend, berechnet)
- Zugeordnete Cards (Referenz)
- Versionsnummer des Produkts als String mit Formatprüfung (V0.0.0.0 mit 10er Stellen)
- Sprintnummmer (lesend, berechnet)
- Sprint Story/Ziel (String)
- SprintStatus (in Plannung, Freigabe, ...)

**Sprint Status**
  * _InPlanning_: Der Sprint befindet sich in Plannung (Default State)
  * _Planned_: Der Sprint wurde im Sprint Planning freigegeben
    * PO gibt Sprint frei
  * _In Progress_: Der Sprint läuft im Moment
    * autom. Gesetzt bei erreichen von Startdatum -> Übertrag der Cards in SB Next Lane
  * _Done_: Sprint wurde fertig bearbeitet und ist zu Ende
    * autom. Gesetzt bei erreichen des Enddatums
  * _Accepted_: Sprint wurde in Sprint Review abgenommen
    * PO hat Sprint mit Team gereviewt-> PO setzt den Status -> Bereit für Archivierung

**Card Status**
  * _New_: Card wurde neu angelegt (Default State)
  * _Planned_: Card wurde in einem Sprint verplant
  * _NotStarted_: Card noch nicht bearbeitet
    * autom. Gesetzt bei Aufenthalt in Next Lane in SB
  * _In Progress_: Card wird bearbeitet
    * autom. Gesetzt bei Aufenthalt in Doing Lane in SB
  * _Done_: (Card wurde fertig bearbeitet)
    * autom. Gesetzt bei Aufenthalt in Done Lane in SB    
  * _Accepted_: Card wurde in Sprint Review abgenommen
    * PO setzt den Status im Sprint Review -> Bereit für Archivierung

**Comment by husKyRe** [comment]
Wie kann man für Front End Funktion für Zuordnung von Card für Sprints anbieten???

**Comment by husKyRe** [comment]
Über NotStarted sollte noch diskutiert werden

**Comment by HD-plus** [comment]
@husKyRe  Ich vermute mal mit 
Sprint Status auf in Progess setzen, wenn Sprint zuvor in **Released** und das Startdatum des Sprints erreicht.
ist
Sprint Status auf in Progess setzen, wenn Sprint zuvor in **in Planning** und das Startdatum des Sprints erreicht.
gemeint?

**Comment by husKyRe** [comment]
Automatische Aktionen wurden nicht umgesetzt. Auf Bitte von @HD-plus soll diese verschoben werden. Aktionen als neuen Issue auslösen

**Comment by husKyRe** [comment]
Aktionen wurden #6 und #86 ergänzt
