### ISSUE TITLE
Redesign: Feature und Task Card

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#73]
Für die Umsetzung von der Planungshilfe auf MVP
Für Feature Card in der Detailansicht eine Darstellung zusätzlich für Steplisten desginen. Parallel zu der Task Card Liste. Vielleicht als Tabs???

In der Lane Ansicht von Feature Card. Darstellung der offenen Steps???

**Comment by FunkyVonTunky** [comment]
@husKyRe ich verstehe das leider noch nicht so ganz wo das genau hin soll und wie es dann funktioniert. Also ein Task ist ja quasi eine detailliertere Steplist...

**Comment by FunkyVonTunky** [comment]
<img width="508" alt="Bildschirmfoto 2020-05-26 um 16 27 19" src="https://user-images.githubusercontent.com/61056122/82912823-cf83e280-9f6d-11ea-83b2-eb0b115744a6.png">

könnte sonst so aussehen... aber die Frage ist dann auch was mit den "Steps" passiert (also sind die dann ein Task oder lassen sie sich dazu umwandeln? - macht die Sache nicht unbedingt einfacher und intuitiver... Ich persönlich würde es eher weglassen.

**Comment by husKyRe** [comment]
Meinst das wir bei den Features die Steps weglassen und erst zu einem späteren Zeitpunkt mit den Task auch die Steps dazu kommen?

**Comment by husKyRe** [comment]
Muss nicht gemacht werden, da nach Absprache mit Stakeholder. Einer  Umsetzung von der Planungshilfe nach MVP wurde von SH nicht als relevant bzgl. für das Sprintplaning
