### ISSUE TITLE
Feature und Epic ist notwendig um Task anzulegen

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#76]
Für das Erstellen von Task ist es notwendig min. ein Epic oder Featrure im Board zu haben.

*gewünschtes Verhalten:*
Es soll aber auch möglich sein. in einem Board nur Tasks anzulegen ohne ein Feature oder Epic. Also muss ein Task nicht immer eine Zuordnung zu einem Feature oder Epic..

**Comment by HD-plus** [comment]
Nun wird automatisch die ID 1 bei der Lane und dem Feature vergeben. Somit kann Beides ausgelassen werden
![image](https://user-images.githubusercontent.com/60195758/86966103-d86cf400-c168-11ea-8ee4-3ddd6f2d0460.png)
