### ISSUE TITLE
API Sync up mit Front End

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#80]
Aufgrund von weiteren Feature Implementierung, muss die Strutur und der Aufbau der API umstrukturiert werden.

Diskussion und Umbau von API für weiteres Vorgehen im Front End

[VorschlagGrundstrukturAPI](https://github.com/scrmtl/server/files/4909380/API_ScrumTool.docx)

**Comment by HD-plus** [comment]
Die Struktur haben wir doch? @husKyRe @zed92 
Wenn ein Get auf [http://scrmtl.ddns.net:14444/api/board/1/?DetailLevel=detail](http://scrmtl.ddns.net:14444/api/board/1/?DetailLevel=detail) ausgeführt wird, kommt ja das folgende Ergebnis:

- [response.txt](https://github.com/scrmtl/server/files/4913201/response.txt)
