### ISSUE TITLE
Sprint Planning Automatik

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#86]
**Sprint Planning Automatik**
Damit das System optimal unterstützen kann, müssen bestimmte Aufgaben dem User abgenommen werden, damit er den Kopf frei für neue Ideen hat. Deshalb wird eine mit Hilfe von Flows (autom. Funktionen) dem Nutzer der Alltag erleichtert
- [x] Sprint auf Status _In Progress_ setzen
 Bedingungen: 
   - [x]  min eine Card in Sprint verplannt, 
   - [x] Sprint ist freigegeben (Status: _Planned_)  
   - [x] Sprint Anfangsdatum erreicht 

- [x] Cards, die in einen Sprint verplannt sind werden. Verbleiben im PB bis zum Start des Sprints. Danach werden sie ins SB in die Next Lane verschoben

- [x] Alle verplannten Cards vom PB (Lane: "Growning (for Refinement)" ) in SB (Lane: "Next (Sprint Backlog)") verschieben. (Card ebenfalls Statuswechsel)
Bedingung:
   - [x] Sprint in Status _In Progress_ 
   - [x] Aktueller Tag zwischen Start und Enddatum liegt
   - [x] Wenn Sprint Attribut einer Card nicht null ist, sondern einer Sprint ID entspricht.
   - [x] Es sollte auch während der Sprint läuft ein Transfer von Cards von PB in SB mögl., um mögliche Spikes zu reaslisieren

- [x] Sprint auf _Done_ setzen
Bedingung:
   - [x] Sprint in Status _In Progress_ 
   - [x] Sprint Enddatum erreicht 

- [x] Sprint auf _Accepted_ setzen
Bedingungen:
   - [x] Sprint in Status _Done_
   - [x] alle zugeordneten Cards haben den Zustand _Accepted_ 
   - [x] Sprint Enddatum erreicht 

Technische Voraussetzungen
- [x] scheduler finden
- [x] scheduler in docker Container Laufzeit integrieren
   - [x] Start bash script erstellen
   - [x] Dockerfile anpassen

**Status Changer**
Bei gewissen Statis aus Seq Diagramm setzt das System die Statis anhand von Uhrzeit und Co.

 - [x] Wird Card auf die Lane Doing im SB gesetzt, bekommt Sie den Status _In Progress_
 - [x] Wird Card auf die Lane Done im SB gesetzt, bekommt Sie den Status _Done_
 - [x] Wird Card auf die Lane Next im SB gesetzt, bekommt Sie den Status _Not Started_ (Bei Transfer von PB muss dies Backend übernehmen)

**Comment by husKyRe** [comment]
Wurden schon umgesetzt
- Wird Card auf die Lane Doing im SB gesetzt, bekommt Sie den Status In Progress

- Wird Card auf die Lane Done im SB gesetzt, bekommt Sie den Status Done

**Comment by husKyRe** [comment]
Würde SP 13 geben

**Comment by husKyRe** [comment]
@HD-plus 
   - Wenn Sprint Attribut einer Card nicht null ist, sondern einer Sprint ID entspricht.
   - Es sollte auch während der Sprint läuft ein Transfer von Cards von PB in SB mögl., um mögliche Spikes zu reaslisieren

Hinzugefügt um mögliche Änderungen während dem Sprint zu realisieren.

**Comment by HD-plus** [comment]
>   @HD-plus 
>    - Wenn Sprint Attribut einer Card nicht null ist, sondern einer Sprint ID entspricht.

Passt habe ich integriert. 

>    - Es sollte auch während der Sprint läuft ein Transfer von Cards von PB in SB mögl., um mögliche Spikes zu reaslisieren
> 
> Hinzugefügt um mögliche Änderungen während dem Sprint zu realisieren.
> 
> Hier müsste der Scheuduler vielleich häufiger laufen

Sollte das dann der Benutzer vielleicht einfach händisch machen? Oder das Frontend ändert das im Backend?

**Comment by husKyRe** [comment]
**Fehler**
- Der Status der verschoben Cards in Next wird nicht auf _Not Started_ geändert 
-

**Comment by HD-plus** [comment]
> **Fehler**
> 
>     * Der Status der verschoben Cards in Next wird nicht auf _Not Started_ geändert
> 
>     * Sprint können nicht mehr geplant bzw. verändert werden, da Backend nun fehler auswirft, z.b. sprint in release setzen oder Story hinzufügen
>       ![image](https://user-images.githubusercontent.com/60154287/104015345-c1a96780-51b4-11eb-88d1-904fa55628ef.png)

der Bug ist behoben
