### ISSUE TITLE
Einfache Statistik Berechnung für das Projekt

### ISSUE THREAD

**Issue by husKyRe** [scrmtl/server#87]
Als SM oder PO möchte ich Statistiken innerhalb eines Projekt sehen, um den Fortschritt zu tracken zu können. Außderdem soll das Burndaown Diagramm im Projektkontext, respektive Product Backlog soll als Plannungshilfe dienen.

- [x] Platzierung auf Dashboard View

- [x] API für Statistic entwerfen
   - [x] Summe der SP im Projekt (erledigt und offen in Summe)
   - [x] Summe der abgeschlossenen SP (Status: Done) im Projekt  
   - [x] Summe der abgeschlossenen SP (Status: Accepted)im Projekt 

   - [x] Summe der Anzahl der Tasks (insgesamt) im Projekt 
   - [x] Summe der Anzahl der Tasks (bewertet, aber nicht abgeschlossen(Done&Accepted)) im Projekt 
   - [x] Summe der abgeschlossenen Anzahl der Tasks (Status: Done) im Projekt 
   - [x] Summe der abgeschlossenen Anzahl der Tasks (Status: Accepted) im Projekt 

   - [x] Durchschnitt der erledigten Task über die (accepted) Sprints im ganze Projekt gesehen (Status: Accepted)
   - [x] Durchschnitt der erledigten SP über die (accepted) Sprints im ganze Projekt gesehen (Status: Accepted)
   - [x] Die drei schlechtesten (accepted) Sprints (SP bezogen)
   - [x] Die drei schlechtesten (accepted) Sprints (Anzahl Tasks bezogen)

- [x] Diagramm für Product Backlog, also über das Projekt hinweg
- [x] Anbinden an die Backend API

**Daten**
- Summe der SP im Projekt (erledigt und offen in Summe)
- Summe der abgeschlossenen SP (Status: Done) im Projekt 
- Summe der abgeschlossenen SP (Status: Accepted)im Projekt 

- Summe der Anzahl der Tasks (insgesamt) im Projekt 
- Summe der Anzahl der Tasks (bewertet, aber nicht abgeschlossen) im Projekt 
- Summe der abgeschlossenen Anzahl der Tasks (Status: Done) im Projekt 
- Summe der abgeschlossenen Anzahl der Tasks (Status: Accepted) im Projekt 

- Durchschnitt der erledigten Task über die Sprints im ganze Projekt gesehen (Status: Accepted)
- Durchschnitt der erledigten SP über die Sprints im ganze Projekt gesehen (Status: Accepted)
- Die drei schlechtesten Sprints (SP bezogen)
- Die drei schlechtesten Sprints (Anzahl Tasks bezogen)

**Graph**

- Tatsächlich abgeschlossene SP auf die Sprints bezogen (Status: Accepted) (Balken)
- Tatsächlich abgeschlossene Tasks auf die Sprints bezogen (Status: Accepted) (Balken)
- Durchschnitt der erledigten Task über die Sprints im ganze Projekt gesehen (Status: Accepted) (Horizontale  Vergleichslinie)
- Durchschnitt der erledigten SP über die Sprints im ganze Projekt gesehen (Status: Accepted) (Horizontale  Vergleichslinie)
y-achse: SP oder Taskanzahl
x-achse: Sprints
Siehe Layout ähnlich wie Sprint Diagramm nur für Projekt
![Statistics](https://user-images.githubusercontent.com/60154287/95125090-ba596480-0754-11eb-98ca-3ae3aa44c90d.png)

**Comment by TheDream3r** [comment]
Ich habe das soweit vorbereitet und mal den Punkt "Anbinden an die Backend API" hinzugefügt. Dann kann ich das anbinden, wenn Herrmann fertig ist

**Comment by husKyRe** [comment]
Bei Seitenwechsel werden daten nicht erneut geladen. Datenanbindung sollte verändert werden

**Comment by husKyRe** [comment]
Bug fixing: Datenanbindung habe ich korregiert. War ein Problem im custom getter und in der Art wie die Daten geladen werden. Habe es nun mit computed properties gelöst.

Außerdem habe ich noch die Darstellung auf Balken geändert, wie es im Issue beschrieben ist.

**Comment by TheDream3r** [comment]
Leider ist es aktuell noch nicht möglich, zwei Bars im Chart nebeneinander zu platzieren. Diese werden aktuell immer überlagert. Das Feature soll aber in den nächsten Monaten kommen: 
https://github.com/plotly/plotly.js/issues/4914
